-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [brainfuck]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace brainfuck

/-- [core::convert::num::ptr_try_from_impls::{impl core::convert::TryFrom<i64, core::num::error::TryFromIntError> for usize}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 279:12-279:64
    Name pattern: [core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, i64, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, i64, core::num::error::TryFromIntError>}::try_from"]
axiom Usize.Insts.CoreConvertTryFromI64TryFromIntError.try_from
  :
  Std.I64 → Result (core.result.Result Std.Usize
    core.num.error.TryFromIntError)

/-- [core::convert::num::ptr_try_from_impls::{impl core::convert::TryFrom<usize, core::num::error::TryFromIntError> for i64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 302:12-302:64
    Name pattern: [core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<i64, usize, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<i64, usize, core::num::error::TryFromIntError>}::try_from"]
axiom I64.Insts.CoreConvertTryFromUsizeTryFromIntError.try_from
  :
  Std.Usize → Result (core.result.Result Std.I64
    core.num.error.TryFromIntError)

/-- [core::mem::maybe_uninit::MaybeUninit]
    Source: '/rustc/library/core/src/mem/maybe_uninit.rs', lines 355:0-355:24
    Name pattern: [core::mem::maybe_uninit::MaybeUninit]
    Visibility: public -/
@[rust_type "core::mem::maybe_uninit::MaybeUninit"]
axiom core.mem.maybe_uninit.MaybeUninit (T : Type) : Type

/-- [core::num::error::{impl core::fmt::Debug for core::num::error::TryFromIntError}::fmt]:
    Source: '/rustc/library/core/src/num/error.rs', lines 9:9-9:14
    Name pattern: [core::num::error::{core::fmt::Debug<core::num::error::TryFromIntError>}::fmt]
    Visibility: public -/
@[rust_fun
  "core::num::error::{core::fmt::Debug<core::num::error::TryFromIntError>}::fmt"]
axiom core.num.error.TryFromIntError.Insts.CoreFmtDebug.fmt
  :
  core.num.error.TryFromIntError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [core::num::error::{impl core::fmt::Debug for core::num::error::TryFromIntError}]
    Source: '/rustc/library/core/src/num/error.rs', lines 9:9-9:14
    Name pattern: [core::fmt::Debug<core::num::error::TryFromIntError>] -/
@[reducible, rust_trait_impl
  "core::fmt::Debug<core::num::error::TryFromIntError>"]
def core.num.error.TryFromIntError.Insts.CoreFmtDebug : core.fmt.Debug
  core.num.error.TryFromIntError := {
  fmt := core.num.error.TryFromIntError.Insts.CoreFmtDebug.fmt
}

/-- [core::num::{i64}::checked_neg]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1341:8-1341:54
    Name pattern: [core::num::{i64}::checked_neg]
    Visibility: public -/
@[rust_fun "core::num::{i64}::checked_neg"]
axiom core.num.I64.checked_neg : Std.I64 → Result (Option Std.I64)

/-- [core::option::{core::option::Option<T>}::and_then]:
    Source: '/rustc/library/core/src/option.rs', lines 1537:4-1539:61
    Name pattern: [core::option::{core::option::Option<@T>}::and_then]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::and_then"]
axiom core.option.Option.and_then
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTOptionInst :
  core.ops.function.FnOnce F T (Option U)) :
  Option T → F → Result (Option U)

/-- [core::option::{core::option::Option<&'_0 T>}::copied]:
    Source: '/rustc/library/core/src/option.rs', lines 2131:4-2133:16
    Name pattern: [core::option::{core::option::Option<&'0 @T>}::copied]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::copied"]
axiom core.option.OptionShared0T.copied
  {T : Type} (markerCopyInst : core.marker.Copy T) :
  Option T → Result (Option T)

/-- [core::result::{core::result::Result<T, E>}::ok]:
    Source: '/rustc/library/core/src/result.rs', lines 709:4-712:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::ok]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
axiom core.result.Result.ok
  {T : Type} {E : Type} : core.result.Result T E → Result (Option T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2872:4-2872:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [brainfuck::analysis::Instr]
    Source: 'src/analysis.rs', lines 22:0-39:1
    Visibility: public -/
@[discriminant isize]
inductive analysis.Instr where
| Inc : analysis.Instr
| Dec : analysis.Instr
| Left : analysis.Instr
| Right : analysis.Instr
| Input : analysis.Instr
| Output : analysis.Instr
| BeginLoop : analysis.Instr
| EndLoop : analysis.Instr

/-- [brainfuck::analysis::{impl core::cmp::PartialEq<brainfuck::analysis::Instr> for brainfuck::analysis::Instr}::eq]:
    Source: 'src/analysis.rs', lines 20:29-20:38
    Visibility: public -/
def analysis.Instr.Insts.CoreCmpPartialEqInstr.eq
  (self : analysis.Instr) (other : analysis.Instr) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [brainfuck::analysis::Program]
    Source: 'src/analysis.rs', lines 42:0-45:1
    Visibility: public -/
structure analysis.Program where
  instructions : alloc.vec.Vec analysis.Instr
  loop_jump_offset : alloc.vec.Vec Std.U32

/-- [brainfuck::interpreter::RunError]
    Source: 'src/interpreter/mod.rs', lines 10:0-12:1
    Visibility: public -/
@[discriminant isize]
inductive interpreter.RunError where
| FuelExhausted : interpreter.RunError

/-- [brainfuck::interpreter::TapeSnapshot]
    Source: 'src/interpreter/mod.rs', lines 16:0-20:1
    Visibility: public -/
structure interpreter.TapeSnapshot where
  left : alloc.vec.Vec Std.U64
  cur : Std.U64
  right : alloc.vec.Vec Std.U64

/-- [brainfuck::interpreter::StateSnapshot]
    Source: 'src/interpreter/mod.rs', lines 24:0-28:1
    Visibility: public -/
structure interpreter.StateSnapshot where
  tape : interpreter.TapeSnapshot
  input : alloc.vec.Vec Std.U64
  output : alloc.vec.Vec Std.U64

/-- [brainfuck::interpreter::Tape]
    Source: 'src/interpreter/mod.rs', lines 30:0-34:1 -/
structure interpreter.Tape where
  negative : alloc.vec.Vec Std.U64
  nonnegative : alloc.vec.Vec Std.U64
  head : Std.I64

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::new]:
    Source: 'src/interpreter/mod.rs', lines 37:4-43:5 -/
def interpreter.Tape.new : Result interpreter.Tape := do
  let y ←
    lift (Std.Array.to_slice (Array.make 1#usize [ 0#u64 ] : Array Std.U64
      1#usize))
  let ret := alloc.slice.Slice.into_vec y
  ok
    {
      negative := (alloc.vec.Vec.new Std.U64),
      nonnegative := ret,
      head := 0#i64
    }

/-- [brainfuck::interpreter::negative_index]:
    Source: 'src/interpreter/mod.rs', lines 99:0-105:1 -/
def interpreter.negative_index (position : Std.I64) : Result Std.I64 := do
  let o ← core.num.I64.checked_neg position
  let i ← core.option.Option.expect o (toStr "position negation overflow")
  let o1 ← lift (I64.checked_sub i 1#i64)
  core.option.Option.expect o1 (toStr "position index overflow")

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::current]:
    Source: 'src/interpreter/mod.rs', lines 45:4-59:5 -/
def interpreter.Tape.current
  (self : interpreter.Tape) :
  Result (Std.U64 × (Std.U64 → interpreter.Tape))
  := do
  let r ← Usize.Insts.CoreConvertTryFromI64TryFromIntError.try_from self.head
  match r with
  | core.result.Result.Ok index =>
    let i := alloc.vec.Vec.len self.nonnegative
    let v ←
      if index >= i
      then
        do
        let i1 ← index + 1#usize
        alloc.vec.Vec.resize core.clone.CloneU64 self.nonnegative i1 0#u64
      else ok self.nonnegative
    let (i1, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U64) v
        index
    let back :=
      fun i2 => let v1 := index_mut_back i2
                { self with nonnegative := v1 }
    ok (i1, back)
  | core.result.Result.Err _ =>
    let flipped ← interpreter.negative_index self.head
    let r1 ←
      Usize.Insts.CoreConvertTryFromI64TryFromIntError.try_from flipped
    let index ←
      core.result.Result.expect
        core.num.error.TryFromIntError.Insts.CoreFmtDebug r1 (toStr
        "negative head index fits in usize")
    let i := alloc.vec.Vec.len self.negative
    let v ←
      if index >= i
      then
        do
        let i1 ← index + 1#usize
        alloc.vec.Vec.resize core.clone.CloneU64 self.negative i1 0#u64
      else ok self.negative
    let (i1, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U64) v
        index
    let back :=
      fun i2 => let v1 := index_mut_back i2
                { self with negative := v1 }
    ok (i1, back)

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::get]:
    Source: 'src/interpreter/mod.rs', lines 61:4-69:5 -/
def interpreter.Tape.get
  (self : interpreter.Tape) (position : Std.I64) : Result Std.U64 := do
  let r ← Usize.Insts.CoreConvertTryFromI64TryFromIntError.try_from position
  match r with
  | core.result.Result.Ok index =>
    let s := alloc.vec.Vec.deref self.nonnegative
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U64) s
        index
    let o1 ← core.option.OptionShared0T.copied core.marker.CopyU64 o
    ok (core.option.Option.unwrap_or o1 0#u64)
  | core.result.Result.Err _ =>
    let flipped ← interpreter.negative_index position
    let r1 ←
      Usize.Insts.CoreConvertTryFromI64TryFromIntError.try_from flipped
    let index ←
      core.result.Result.expect
        core.num.error.TryFromIntError.Insts.CoreFmtDebug r1 (toStr
        "negative position index fits in usize")
    let s := alloc.vec.Vec.deref self.negative
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U64) s
        index
    let o1 ← core.option.OptionShared0T.copied core.marker.CopyU64 o
    ok (core.option.Option.unwrap_or o1 0#u64)

/-- [brainfuck::interpreter::trim_trailing_zeros]: loop body 0:
    Source: 'src/interpreter/mod.rs', lines 108:4-114:1 -/
@[rust_loop_body]
def interpreter.trim_trailing_zeros_loop.body
  (cells : alloc.vec.Vec Std.U64) :
  Result (ControlFlow (alloc.vec.Vec Std.U64) (alloc.vec.Vec Std.U64))
  := do
  let (o, cells1) ← alloc.vec.Vec.pop Global cells
  match o with
  | none => ok (done cells1)
  | some value =>
    if value != 0#u64
    then let cells2 ← alloc.vec.Vec.push cells1 value
         ok (done cells2)
    else ok (cont cells1)

/-- [brainfuck::interpreter::trim_trailing_zeros]: loop 0:
    Source: 'src/interpreter/mod.rs', lines 108:4-114:1 -/
@[rust_loop]
def interpreter.trim_trailing_zeros_loop
  (cells : alloc.vec.Vec Std.U64) : Result (alloc.vec.Vec Std.U64) := do
  loop
    (fun cells1 => interpreter.trim_trailing_zeros_loop.body cells1)
    cells

/-- [brainfuck::interpreter::trim_trailing_zeros]:
    Source: 'src/interpreter/mod.rs', lines 107:0-114:1 -/
@[reducible]
def interpreter.trim_trailing_zeros
  (cells : alloc.vec.Vec Std.U64) : Result (alloc.vec.Vec Std.U64) := do
  interpreter.trim_trailing_zeros_loop cells

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::snapshot]: loop body 0:
    Source: 'src/interpreter/mod.rs', lines 79:8-82:9 -/
@[rust_loop_body]
def interpreter.Tape.snapshot_loop0.body
  (v : alloc.vec.Vec Std.U64) (v1 : alloc.vec.Vec Std.U64) (i : Std.I64)
  (lowest : Std.I64) (left : alloc.vec.Vec Std.U64) (position : Std.I64) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.I64) (alloc.vec.Vec
    Std.U64))
  := do
  if position >= lowest
  then
    let i1 ←
      interpreter.Tape.get { negative := v, nonnegative := v1, head := i }
        position
    let left1 ← alloc.vec.Vec.push left i1
    let position1 ← position - 1#i64
    ok (cont (left1, position1))
  else ok (done left)

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::snapshot]: loop 0:
    Source: 'src/interpreter/mod.rs', lines 79:8-82:9 -/
@[rust_loop]
def interpreter.Tape.snapshot_loop0
  (v : alloc.vec.Vec Std.U64) (v1 : alloc.vec.Vec Std.U64) (i : Std.I64)
  (lowest : Std.I64) (left : alloc.vec.Vec Std.U64) (position : Std.I64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (left1, position1) => interpreter.Tape.snapshot_loop0.body v v1 i
      lowest left1 position1)
    (left, position)

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::snapshot]: loop body 1:
    Source: 'src/interpreter/mod.rs', lines 85:8-88:9 -/
@[rust_loop_body]
def interpreter.Tape.snapshot_loop1.body
  (v : alloc.vec.Vec Std.U64) (v1 : alloc.vec.Vec Std.U64) (i : Std.I64)
  (highest : Std.I64) (right : alloc.vec.Vec Std.U64) (position : Std.I64) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.I64) (alloc.vec.Vec
    Std.U64))
  := do
  if position <= highest
  then
    let i1 ←
      interpreter.Tape.get { negative := v, nonnegative := v1, head := i }
        position
    let right1 ← alloc.vec.Vec.push right i1
    let position1 ← position + 1#i64
    ok (cont (right1, position1))
  else ok (done right)

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::snapshot]: loop 1:
    Source: 'src/interpreter/mod.rs', lines 85:8-88:9 -/
@[rust_loop]
def interpreter.Tape.snapshot_loop1
  (v : alloc.vec.Vec Std.U64) (v1 : alloc.vec.Vec Std.U64) (i : Std.I64)
  (highest : Std.I64) (right : alloc.vec.Vec Std.U64) (position : Std.I64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (right1, position1) => interpreter.Tape.snapshot_loop1.body v v1 i
      highest right1 position1)
    (right, position)

/-- [brainfuck::interpreter::{brainfuck::interpreter::Tape}::snapshot]:
    Source: 'src/interpreter/mod.rs', lines 71:4-96:5 -/
def interpreter.Tape.snapshot
  (self : interpreter.Tape) : Result interpreter.TapeSnapshot := do
  let i := alloc.vec.Vec.len self.negative
  let r ← I64.Insts.CoreConvertTryFromUsizeTryFromIntError.try_from i
  let o ← core.result.Result.ok r
  let o1 ←
    core.option.Option.and_then (BuiltinFnOnce Std.I64 (Option Std.I64)) o
      (core.num.I64.checked_neg)
  let lowest ←
    core.option.Option.expect o1 (toStr "negative tape length fits in i64")
  let i1 := alloc.vec.Vec.len self.nonnegative
  let r1 ← I64.Insts.CoreConvertTryFromUsizeTryFromIntError.try_from i1
  let i2 ←
    core.result.Result.expect core.num.error.TryFromIntError.Insts.CoreFmtDebug
      r1 (toStr "tape length fits in i64")
  let highest ← i2 - 1#i64
  let o2 ← lift (I64.checked_sub self.head 1#i64)
  let position ← core.option.Option.expect o2 (toStr "head - 1 fits in i64")
  let left ←
    interpreter.Tape.snapshot_loop0 self.negative self.nonnegative self.head
      lowest (alloc.vec.Vec.new Std.U64) position
  let o3 ← lift (I64.checked_add self.head 1#i64)
  let position1 ← core.option.Option.expect o3 (toStr "head + 1 fits in i64")
  let right ←
    interpreter.Tape.snapshot_loop1 self.negative self.nonnegative self.head
      highest (alloc.vec.Vec.new Std.U64) position1
  let left1 ← interpreter.trim_trailing_zeros left
  let right1 ← interpreter.trim_trailing_zeros right
  let i3 ← interpreter.Tape.get self self.head
  ok { left := left1, cur := i3, right := right1 }

/-- [brainfuck::interpreter::exec]: loop body 0:
    Source: 'src/interpreter/mod.rs', lines 0:0-176:1 -/
@[rust_loop_body]
def interpreter.exec_loop.body
  (program : analysis.Program) (input : Slice Std.U64)
  (tape : interpreter.Tape) (pc : Std.Usize) (next_input : Std.Usize)
  (output : alloc.vec.Vec Std.U64) (remaining : Std.U64) :
  Result (ControlFlow (interpreter.Tape × Std.Usize × Std.Usize ×
    (alloc.vec.Vec Std.U64) × Std.U64) (core.result.Result
    interpreter.StateSnapshot interpreter.RunError))
  := do
  let i := alloc.vec.Vec.len program.instructions
  if pc < i
  then
    let instr ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        analysis.Instr) program.instructions pc
    let b ←
      analysis.Instr.Insts.CoreCmpPartialEqInstr.eq instr
        analysis.Instr.EndLoop
    if b
    then
      let i1 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32)
          program.loop_jump_offset pc
      let pc1 ← lift (UScalar.cast .Usize i1)
      ok (cont (tape, pc1, next_input, output, remaining))
    else
      if remaining = 0#u64
      then
        ok (done (core.result.Result.Err interpreter.RunError.FuelExhausted))
      else
        let remaining1 ← remaining - 1#u64
        let (tape1, pc1, next_input1, output1) ←
          match instr with
          | analysis.Instr.Inc =>
            do
            let (cell, current_back) ← interpreter.Tape.current tape
            let cell1 ← lift (core.num.U64.wrapping_add cell 1#u64)
            let tape2 := current_back cell1
            ok (tape2, pc, next_input, output)
          | analysis.Instr.Dec =>
            do
            let (cell, current_back) ← interpreter.Tape.current tape
            let cell1 ← lift (core.num.U64.wrapping_sub cell 1#u64)
            let tape2 := current_back cell1
            ok (tape2, pc, next_input, output)
          | analysis.Instr.Left =>
            do
            let o ← lift (I64.checked_sub tape.head 1#i64)
            let i1 ←
              core.option.Option.expect o (toStr "tape head underflow")
            ok ({ tape with head := i1 }, pc, next_input, output)
          | analysis.Instr.Right =>
            do
            let o ← lift (I64.checked_add tape.head 1#i64)
            let i1 ← core.option.Option.expect o (toStr "tape head overflow")
            ok ({ tape with head := i1 }, pc, next_input, output)
          | analysis.Instr.Input =>
            do
            let o ←
              core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
                Std.U64) input next_input
            let o1 ← core.option.OptionShared0T.copied core.marker.CopyU64 o
            let value ← lift (core.option.Option.unwrap_or o1 0#u64)
            let i1 ← next_input + 1#usize
            let i2 := Slice.len input
            let next_input2 ←
              core.cmp.Ord.min.trait_default core.cmp.OrdUsize i1 i2
            let (_, current_back) ← interpreter.Tape.current tape
            let tape2 := current_back value
            ok (tape2, pc, next_input2, output)
          | analysis.Instr.Output =>
            do
            let (i1, current_back) ← interpreter.Tape.current tape
            let output2 ← alloc.vec.Vec.push output i1
            let tape2 := current_back i1
            ok (tape2, pc, next_input, output2)
          | analysis.Instr.BeginLoop =>
            do
            let (i1, current_back) ← interpreter.Tape.current tape
            let (t, i2) ←
              if i1 = 0#u64
              then
                do
                let i3 ←
                  alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                    Std.U32) program.loop_jump_offset pc
                let pc2 ← lift (UScalar.cast .Usize i3)
                let tape2 := current_back i1
                ok (tape2, pc2)
              else let tape2 := current_back i1
                   ok (tape2, pc)
            ok (t, i2, next_input, output)
          | analysis.Instr.EndLoop => fail panic
        let pc2 ← pc1 + 1#usize
        ok (cont (tape1, pc2, next_input1, output1, remaining1))
  else
    let ts ← interpreter.Tape.snapshot tape
    let s ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U64) input
        { start := next_input }
    let v ← alloc.slice.Slice.to_vec core.clone.CloneU64 s
    ok (done (core.result.Result.Ok { tape := ts, input := v, output }))

/-- [brainfuck::interpreter::exec]: loop 0:
    Source: 'src/interpreter/mod.rs', lines 0:0-176:1 -/
@[rust_loop]
def interpreter.exec_loop
  (program : analysis.Program) (input : Slice Std.U64)
  (tape : interpreter.Tape) (pc : Std.Usize) (next_input : Std.Usize)
  (output : alloc.vec.Vec Std.U64) (remaining : Std.U64) :
  Result (core.result.Result interpreter.StateSnapshot interpreter.RunError)
  := do
  loop
    (fun (tape1, pc1, next_input1, output1, remaining1) =>
      interpreter.exec_loop.body program input tape1 pc1 next_input1 output1
      remaining1)
    (tape, pc, next_input, output, remaining)

/-- [brainfuck::interpreter::exec]:
    Source: 'src/interpreter/mod.rs', lines 116:0-176:1 -/
def interpreter.exec
  (program : analysis.Program) (input : Slice Std.U64) (fuel : Std.U64) :
  Result (core.result.Result interpreter.StateSnapshot interpreter.RunError)
  := do
  let i ← lift (IScalar.hcast .U64 core.num.I64.MAX)
  massert (fuel <= i)
  let tape ← interpreter.Tape.new
  interpreter.exec_loop program input tape 0#usize 0#usize (alloc.vec.Vec.new
    Std.U64) fuel

/-- [brainfuck::interpreter::run_full]:
    Source: 'src/interpreter/mod.rs', lines 182:0-187:1
    Visibility: public -/
def interpreter.run_full
  (program : analysis.Program) (input : Slice Std.U64) (fuel : Std.U64) :
  Result (core.result.Result interpreter.StateSnapshot interpreter.RunError)
  := do
  interpreter.exec program input fuel

end brainfuck
