/-
  The Aeneas-generated pure model of the Rust interpreter.

  `BrainfuckCore/Types.lean` and `BrainfuckCore/Funs.lean` are generated by
  `scripts/extract-rust.sh` and must not be edited by hand;
  `BrainfuckCore/TypesExternal.lean` and `BrainfuckCore/FunsExternal.lean`
  are hand-written models of the standard-library leaves.
-/
import BrainfuckCore.Funs
