-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [brainfuck]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import BrainfuckCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open brainfuck

/-- [core::convert::num::ptr_try_from_impls::{impl core::convert::TryFrom<i64, core::num::error::TryFromIntError> for usize}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 279:12-279:64
    Name pattern: [core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, i64, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, i64, core::num::error::TryFromIntError>}::try_from"]
axiom Usize.Insts.CoreConvertTryFromI64TryFromIntError.try_from
  :
  Std.I64 → Result (core.result.Result Std.Usize
    core.num.error.TryFromIntError)

/-- [core::convert::num::ptr_try_from_impls::{impl core::convert::TryFrom<usize, core::num::error::TryFromIntError> for i64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 302:12-302:64
    Name pattern: [core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<i64, usize, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<i64, usize, core::num::error::TryFromIntError>}::try_from"]
axiom I64.Insts.CoreConvertTryFromUsizeTryFromIntError.try_from
  :
  Std.Usize → Result (core.result.Result Std.I64
    core.num.error.TryFromIntError)

/-- [core::num::error::{impl core::fmt::Debug for core::num::error::TryFromIntError}::fmt]:
    Source: '/rustc/library/core/src/num/error.rs', lines 9:9-9:14
    Name pattern: [core::num::error::{core::fmt::Debug<core::num::error::TryFromIntError>}::fmt]
    Visibility: public -/
@[rust_fun
  "core::num::error::{core::fmt::Debug<core::num::error::TryFromIntError>}::fmt"]
axiom core.num.error.TryFromIntError.Insts.CoreFmtDebug.fmt
  :
  core.num.error.TryFromIntError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::num::{i64}::checked_neg]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1341:8-1341:54
    Name pattern: [core::num::{i64}::checked_neg]
    Visibility: public -/
@[rust_fun "core::num::{i64}::checked_neg"]
axiom core.num.I64.checked_neg : Std.I64 → Result (Option Std.I64)

/-- [core::option::{core::option::Option<T>}::and_then]:
    Source: '/rustc/library/core/src/option.rs', lines 1537:4-1539:61
    Name pattern: [core::option::{core::option::Option<@T>}::and_then]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::and_then"]
axiom core.option.Option.and_then
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTOptionInst :
  core.ops.function.FnOnce F T (Option U)) :
  Option T → F → Result (Option U)

/-- [core::option::{core::option::Option<&'_0 T>}::copied]:
    Source: '/rustc/library/core/src/option.rs', lines 2131:4-2133:16
    Name pattern: [core::option::{core::option::Option<&'0 @T>}::copied]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::copied"]
axiom core.option.OptionShared0T.copied
  {T : Type} (markerCopyInst : core.marker.Copy T) :
  Option T → Result (Option T)

/-- [core::result::{core::result::Result<T, E>}::ok]:
    Source: '/rustc/library/core/src/result.rs', lines 709:4-712:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::ok]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
axiom core.result.Result.ok
  {T : Type} {E : Type} : core.result.Result T E → Result (Option T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2872:4-2872:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

