/-
  Hand-written models for the external functions of [brainfuck]: see
  `FunsExternal_Template.lean` (regenerated by `scripts/extract-rust.sh`)
  for the expected signatures.

  These definitions are part of the trusted base of the verification: each
  models a Rust standard-library function that Charon did not translate.
  They are deliberately small and obvious.
-/
import Aeneas
import BrainfuckCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

open brainfuck

/--
  [core::convert::num::ptr_try_from_impls::{impl core::convert::TryFrom<i64,
  core::num::error::TryFromIntError> for usize}::try_from]:
  succeeds exactly on values representable in `usize`.
-/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, i64, core::num::error::TryFromIntError>}::try_from"]
def Usize.Insts.CoreConvertTryFromI64TryFromIntError.try_from
    (i : Std.I64) :
    Result (core.result.Result Std.Usize core.num.error.TryFromIntError) :=
  if 0 ≤ i.val ∧ i.val ≤ (Usize.max : Int) then
    ok (core.result.Result.Ok (IScalar.hcast .Usize i))
  else
    ok (core.result.Result.Err ())

/--
  [core::convert::num::ptr_try_from_impls::{impl core::convert::TryFrom<usize,
  core::num::error::TryFromIntError> for i64}::try_from]:
  succeeds exactly on values representable in `i64`.
-/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<i64, usize, core::num::error::TryFromIntError>}::try_from"]
def I64.Insts.CoreConvertTryFromUsizeTryFromIntError.try_from
    (u : Std.Usize) :
    Result (core.result.Result Std.I64 core.num.error.TryFromIntError) :=
  if (u.val : Int) ≤ I64.max then
    ok (core.result.Result.Ok (UScalar.hcast .I64 u))
  else
    ok (core.result.Result.Err ())

/--
  [core::num::error::{impl core::fmt::Debug for
  core::num::error::TryFromIntError}::fmt]: only reachable through the failure
  path of `Result::expect`, and formatting is unobservable in the model.
-/
@[rust_fun
  "core::num::error::{core::fmt::Debug<core::num::error::TryFromIntError>}::fmt"]
def core.num.error.TryFromIntError.Insts.CoreFmtDebug.fmt
    (_ : core.num.error.TryFromIntError) (f : core.fmt.Formatter) :
    Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter) :=
  ok (core.result.Result.Ok (), f)

/--
  [core::num::{i64}::checked_neg]: negation overflows exactly when
  `0 - i` does, so the library's checked subtraction is a complete model.
-/
@[rust_fun "core::num::{i64}::checked_neg"]
def core.num.I64.checked_neg (i : Std.I64) : Result (Option Std.I64) :=
  ok (I64.checked_sub 0#i64 i)

/-- [core::option::{core::option::Option<T>}::and_then] -/
@[rust_fun "core::option::{core::option::Option<@T>}::and_then"]
def core.option.Option.and_then
    {T : Type} {U : Type} {F : Type}
    (opsfunctionFnOnceFTupleTOptionInst : core.ops.function.FnOnce F T (Option U))
    (o : Option T) (f : F) : Result (Option U) :=
  match o with
  | none   => ok none
  | some x => opsfunctionFnOnceFTupleTOptionInst.call_once f x

/-- [core::option::{core::option::Option<&'_0 T>}::copied] -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::copied"]
def core.option.OptionShared0T.copied
    {T : Type} (markerCopyInst : core.marker.Copy T)
    (o : Option T) : Result (Option T) :=
  ok o

/-- [core::result::{core::result::Result<T, E>}::ok] -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
def core.result.Result.ok
    {T : Type} {E : Type} (r : core.result.Result T E) : Result (Option T) :=
  match r with
  | core.result.Result.Ok v  => Aeneas.Std.Result.ok (some v)
  | core.result.Result.Err _ => Aeneas.Std.Result.ok none

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]: removes and returns the last element. -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
def alloc.vec.Vec.pop
    {T : Type} (A : Type) (v : alloc.vec.Vec T) :
    Result ((Option T) × alloc.vec.Vec T) :=
  ok (v.val.getLast?,
      ⟨v.val.dropLast, by
        have h := v.property
        simp only [List.length_dropLast]
        omega⟩)
