/-
  Hand-written models for the external types of [brainfuck]: see
  `TypesExternal_Template.lean` (regenerated by `scripts/extract-rust.sh`)
  for the expected signatures.
-/
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/--
  [core::mem::maybe_uninit::MaybeUninit]

  Only ever reaches the model through fully-initialized values (it appears in
  the innards of `Vec::resize`), so the initialized model is the honest one.
-/
@[rust_type "core::mem::maybe_uninit::MaybeUninit"]
def core.mem.maybe_uninit.MaybeUninit (T : Type) : Type := T
