-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [brainfuck]: type definitions
import Aeneas
import BrainfuckCore.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace brainfuck

/-- [brainfuck::analysis::Instr]
    Source: 'src/analysis.rs', lines 22:0-39:1
    Visibility: public -/
@[discriminant isize]
inductive analysis.Instr where
| Inc : analysis.Instr
| Dec : analysis.Instr
| Left : analysis.Instr
| Right : analysis.Instr
| Input : analysis.Instr
| Output : analysis.Instr
| BeginLoop : analysis.Instr
| EndLoop : analysis.Instr

/-- [brainfuck::analysis::Program]
    Source: 'src/analysis.rs', lines 42:0-45:1
    Visibility: public -/
structure analysis.Program where
  instructions : alloc.vec.Vec analysis.Instr
  loop_jump_offset : alloc.vec.Vec Std.U32

/-- [brainfuck::interpreter::RunError]
    Source: 'src/interpreter/mod.rs', lines 10:0-12:1
    Visibility: public -/
@[discriminant isize]
inductive interpreter.RunError where
| FuelExhausted : interpreter.RunError

/-- [brainfuck::interpreter::TapeSnapshot]
    Source: 'src/interpreter/mod.rs', lines 16:0-20:1
    Visibility: public -/
structure interpreter.TapeSnapshot where
  left : alloc.vec.Vec Std.U64
  cur : Std.U64
  right : alloc.vec.Vec Std.U64

/-- [brainfuck::interpreter::StateSnapshot]
    Source: 'src/interpreter/mod.rs', lines 24:0-28:1
    Visibility: public -/
structure interpreter.StateSnapshot where
  tape : interpreter.TapeSnapshot
  input : alloc.vec.Vec Std.U64
  output : alloc.vec.Vec Std.U64

/-- [brainfuck::interpreter::Tape]
    Source: 'src/interpreter/mod.rs', lines 30:0-34:1 -/
structure interpreter.Tape where
  negative : alloc.vec.Vec Std.U64
  nonnegative : alloc.vec.Vec Std.U64
  head : Std.I64

end brainfuck
