[package]
name = "brainfuck-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1"
libfuzzer-sys = "0.4"

[dependencies.brainfuck]
path = ".."
features = ["fuzzing"]

[[bin]]
name = "differential"
path = "fuzz_targets/differential.rs"
test = false
doc = false
bench = false

[workspace]
